# Generated by Django 4.2.13 on 2024-06-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_is_active_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='province',
            name='abbreviation',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeLeaveQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_increment_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_weeks', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('monthly_increment', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('paid', models.BooleanField(default=False)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.province')),
            ],
            options={
                'unique_together': {('province', 'leave_type')},
            },
        ),
    ]
