# Generated by Django 4.2.13 on 2024-06-28 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.province'),
        ),
    ]
