# Generated by Django 4.2.13 on 2024-06-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentitlement',
            name='monthly_increment',
            field=models.BooleanField(default=False),
        ),
    ]
