# Generated by Django 4.2.13 on 2024-07-07 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_leaveentitlement_monthly_increment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("shift_start_time", models.TimeField()),
                ("shift_end_time", models.TimeField()),
                ("break_1_start_time", models.TimeField(blank=True, null=True)),
                ("break_1_end_time", models.TimeField(blank=True, null=True)),
                ("lunch_start_time", models.TimeField(blank=True, null=True)),
                ("lunch_end_time", models.TimeField(blank=True, null=True)),
                ("break_2_start_time", models.TimeField(blank=True, null=True)),
                ("break_2_end_time", models.TimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.employee",
                    ),
                ),
            ],
        ),
    ]
