# Generated by Django 4.2.13 on 2024-08-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Off", "Off"),
                            ("LOA", "LOA"),
                            ("Attrition", "Attrition"),
                            ("Training", "Training"),
                            ("Scheduled", "Scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="schedule_status",
                        to="api.schedule",
                    ),
                ),
            ],
        ),
    ]
